# Generated by Django 4.1 on 2024-04-22 21:08

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "sensitive_data",
                    django_cryptography.fields.encrypt(
                        models.CharField(max_length=100)
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("published_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
